cfg = $path.directory($out_root)

if ($config.lockfile.gen)
  pins = $process.run_regex(\
    bpkg pkg-status --all --link -d "$cfg", \
    '^([^!? ][^ ]*) \[[^\]]*\] configured !?([^ ]*).*', \
    '\1/\2')

file{bdep.lock}@./:
{{
  depdb hash $pins

  diag generate $>
  lf = $path($>)
  true > $lf
  for pin: $pins
  {
    echo $pin >> $lf
  }
}}

./: file{bdep.lock}:
{
  include = $config.lockfile.gen
}

./: {*/ -build/} doc{README.md} manifest
